<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>AiPet.Storage</RootNamespace>
    <AssemblyName>AiPet.Storage</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AiPet.Common\AiPet.Common.csproj" />
  </ItemGroup>

</Project>
